#!/bin/bash

export PGPASSWORD="${POSTGRES_PASSWORD}"

psql -U "${POSTGRES_USER}" -d "${POSTGRES_DB}" <<EOF

DO \$\$
BEGIN
    IF NOT EXISTS (
        SELECT FROM pg._catalog.pg_roles WHERE rolname = 'PU_USER'
    ) THEN
        CREATE ROLE ${PU_USER} LOGIN PASSWORD '${PU_USER_PASSWORD}';
    END IF;
END

GRANT CONNECT ON DATABASE ${POSTGRES_DB} TO ${PU_USER};
GRANT USAGE ON SCHEMA public TO ${PU_USER};
GRANT CREATE ON SCHEMA public TO ${PU_USER};
GRANT SELECT, INSERT, UPDATE, DELETE ON ALL TABLES IN SCHEMA public TO ${PU_USER};
ALTER DEFAULT PRIVILEGES IN SCHEMA public GRANT SELECT, INSERT, UPDATE, DELETE ON TABLES TO ${PU_USER};
GRANT USAGE, SELECT ON ALL SEQUENCES IN SCHEMA public TO ${PU_USER};
ALTER DEFAULT PRIVILEGES IN SCHEMA public GRANT USAGE, SELECT ON SEQUENCES TO ${PU_USER};

EOF
